
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
contract Wallet {
    modifier acception() {
        require(msg.pubkey() == tvm.pubkey(), 101);
        tvm.accept();
        _;
    }

    function sendValue_without_fee(address dest, uint128 amount, bool bounce) public view acception{
        dest.transfer(amount, bounce, 0);
    }


    function sendValue_with_fee(address dest, uint128 amount, bool bounce) public view acception{
        dest.transfer(amount, bounce, 1);
    }


    function sendValue_and_destroy(address dest, uint128 amount, bool bounce) public view acception{
        dest.transfer(amount, bounce, 160);
    }
}
